title: HDGenius
subtitle: "The official home of Roy Stewart's work"
email: roythomasstewart@gmail.com
description: >-
  This the the official site for all of Roy Stewart's works.
  Here you can find blog articles, project information, and much more.
baseurl: ""
url: "http://hdgenius.me"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
