title: HDGenius
subtitle: "The official home of Roy Stewart's work"
email: roythomasstewart@gmail.com
description: >-
  This the the official site for all of Roy Stewart's works.
  Here you can find blog articles, project information, and much more.
baseurl: ""
url: "http://hdgenius.me"

markdown: kramdown
remote_theme: roy-stewart/HDJekyll
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

sass:
  sass_dir: _sass
  style: compressed
